### ISSUE TITLE
Provide more examples

### ISSUE THREAD

**Issue by dkniffin** [grosser/codeclimate_batch#6]
I'm trying to add this gem to my project, but I'm having some issues. I think some more documentation would help. Specifically, which files to include this in for each build system (rspec, minitest, cucumber, etc), and what to put in `.travis.yml`

I've included this at the top of `spec/spec_helper.rb`, and `features/support/env.rb`:

``` ruby
if ENV['CI']
  require 'codeclimate_batch'
  CodeclimateBatch.start
end
```

And I added this to my `.travis.yml`:

``` yml
after_script:
  - code-climate-batch --groups 2
```

(and I still have this in there too:)

``` yml
addons:
  code_climate:
    repo_token: <token>
```

When I run a travis build, I'm getting:

``` bash
$ code-climate-batch --groups 2
/home/travis/build.sh: line 45: code-climate-batch: command not found
```

It seems like something is wrong with my path, but I'm not sure what to do to fix it. Should I add `gem install -g codeclimate_batch` as a before_install?

**Comment by dkniffin** [comment]
Doh! I just realized it's `codeclimate-batch`, not `code-climate-batch`. Running again now to see if it fixes it.

**Comment by dkniffin** [comment]
Nope, still no luck:

``` bash
$ codeclimate-batch --groups 2
/home/travis/build.sh: line 45: codeclimate-batch: command not found
```

**Comment by dkniffin** [comment]
Alright, I got it to find the script, with:

``` yml
bundler_args: --binstubs
after_script:
  - ./bin/codeclimate-batch --groups 2
```

but now, it looks like it's not reporting:

```
$ ./bin/codeclimate-batch --groups 2
Code climate: No files found to report
```

**Comment by grosser** [comment]
your tests should show something like "coverage stored in xyz" ... that is where it tries to pick the files up from ... try locally first and see if there is any extra output when running the tests ... files should be generated in `"#{Dir.tmpdir}/codeclimate-test-coverage-*"`

**Comment by dkniffin** [comment]
I think I might have figured it out.

It wasn't doing it locally, because I didn't have the `$CODECLIMATE_REPO_TOKEN` variable set. Once I did that, it worked.

On travis, I believe it wasn't doing it because the gem checks to make sure the branch is master, which wasn't true, because I was looking at a PR build, and I didn't have "Build pushes" enabled in travis.

There's a few changes I think should be made to this repo, with documentation and dependencies. I'll make PRs for those.

**Comment by grosser** [comment]
Can you make a PR to add more docs or warnings for the cases you ran into ?

**Comment by dkniffin** [comment]
Yep, for sure. I'm stilling trying to get it working, but my issues are on CC now, I think.

**Comment by grosser** [comment]
I think you need to have a real build on master or CC will not show anything

**Comment by dkniffin** [comment]
ie: A PR is merged? Yea, I did that. and CC is showing the right commit sha, but not the right test coverage percentage.

**Comment by dkniffin** [comment]
Hmm. As far as I can tell, I'm doing everything right now, but it's still not updating the number in CC.

Here's my travis output:

```
$ ./bin/codeclimate-batch --groups 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23410  100    47  100 23363    929   451k --:--:-- --:--:-- --:--:--  518k
waiting for 1/2 reports on dkniffin-kinship-103
Code climate: 0.07s to send 2 reports
```

**Comment by grosser** [comment]
yes, that should be good ... maybe takes a while to update ... ours shows
"since march 7th" ... so it's 7 days old ...

**Comment by dkniffin** [comment]
Hmm, well in CC I see this:
![image](https://cloud.githubusercontent.com/assets/1680080/13756650/3f55a584-e9f7-11e5-86fe-77bfceac4846.png)

And that's my most recent commit.

**Comment by grosser** [comment]
hmmm idk ... reaching out to their support could help ... to get 'did it
come in' / 'was there an internal error' answered

**Comment by dkniffin** [comment]
Ok, I'll do that.

**Comment by grosser** [comment]
added comment about token and branch to the Readme, hope that helps :)

**Comment by dkniffin** [comment]
I'm still trying to fix this. I've got some updates to the readme made locally, but I'm waiting to hear back from CC support, to make sure everything works, before submitting a PR.
