### ISSUE TITLE
Stopped working on travis after switching to trusty and `sudo: required`

### ISSUE THREAD

**Issue by glebm** [grosser/codeclimate_batch#7]
Now I get:

```
> bundle exec codeclimate-batch --groups 9
Code climate: No files found to report
```

https://travis-ci.org/thredded/db_text_search/jobs/119401094#L402

Before the switch worked just fine:
https://travis-ci.org/thredded/db_text_search/jobs/119310875

The switch happened here: https://github.com/thredded/db_text_search/commit/12395f183e31ba3578bc3fac93190d8b888db70b

Really unsure of why the change to trusty + `sudo: required` broke this.

**Comment by grosser** [comment]
$TMPDIR might have changed ... so the coverage files are dropped in the
wrong location or get somehow discarded ...

But for a simpler explanation: Not seeing any "generated file xyz" and it
did not run on master, but  v0.1.1 ... if that was the master branch then
travis might have changed around how these env variables work, best print
them all out and then see if they match the logic inside of here

**Comment by glebm** [comment]
Here it is running on master with env output, same issue:
https://travis-ci.org/thredded/db_text_search/jobs/119501725#L277
The `TRAVIS_BRANCH` variable is set. `TMPDIR` is not set.

**Comment by grosser** [comment]
CODECLIMATE_REPO_TOKEN is not set

**Comment by glebm** [comment]
Looks like the latest travis silently broke support for the CodeClimate add-on. A work-around is to not use the add-on and set the env var directly:
https://github.com/thredded/db_text_search/commit/057bba6615b190cd0396e03188e362c6422174f0
