### ISSUE TITLE
dependency on cc-amend server?

### ISSUE THREAD

**Issue by afeld** [grosser/codeclimate_batch#8]
This gem appears to rely on an external web service:

https://cc-amend.herokuapp.com

A couple of questions:
- What was the motivation for having the logic as a web service, rather than included in this gem?
- Is the source available anywhere?

Thanks!

/cc @harrisj @mrb

**Comment by grosser** [comment]
- needs an external service or it would not work
- http://lmgtfy.com/?q=github+cc-amend&l=1 :trollface:

**Comment by grosser** [comment]
added a link to the readme
